---
- name: Create user and add SSH key
  hosts: all
  become: yes

  vars_prompt:
    - name: "ssh_public_key"
      prompt: "Enter the contents of the public SSH key (id_rsa.pub) for user1:"
      private: no

  tasks:
    - name: Create user1
      user:
        name: user1
        state: present

    - name: Ensure .ssh directory exists for user1
      file:
        path: "/home/user1/.ssh"
        state: directory
        mode: "0700"
        owner: user1
        group: user1

    - name: Add SSH public key to authorized_keys for user1
      authorized_key:
        user: user1
        state: present
        key: "{{ ssh_public_key }}"