---
# tasks file for vsftpd_role

- name: Install vsftpd package
  apt:
    name: vsftpd
    state: present

- name: Start vsftpd service and enable it on boot
  service:
    name: vsftpd
    state: started
    enabled: yes

